# Generated by Django 4.2.7 on 2023-12-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avantages',
            name='Autres_Ind_Primes',
            field=models.FloatField(default=0),
        ),
    ]
