# Generated by Django 4.2.7 on 2023-12-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_avantages_autres_ind_primes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche_paie',
            name='jours_travaillés',
            field=models.IntegerField(default=0),
        ),
    ]
