# Generated by Django 4.2.7 on 2023-12-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_fiche_paie_jours_travaillés'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche_paie',
            name='val_congé_non_payé',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fiche_paie',
            name='val_congé_payé',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fiche_paie',
            name='val_jours_supp',
            field=models.FloatField(default=0),
        ),
    ]
