# Generated by Django 4.2.7 on 2023-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_fiche_paie_val_ind_présence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congés',
            name='Congé_Annuel',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='congés',
            name='Congé_Annuel_Ce_Mois',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='congés',
            name='Congé_Maladie',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='congés',
            name='Congé_Maladie_Ce_Mois',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='congés',
            name='Congé_Non_Payé',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='congés',
            name='Congé_Non_Payé_Ce_Mois',
            field=models.IntegerField(default=0),
        ),
    ]
