# Generated by Django 4.2.4 on 2023-12-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_fiche_paie_salaire_de_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='période',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Année', models.CharField(default='2023', max_length=4)),
                ('Mois', models.CharField(default='12', max_length=25)),
            ],
        ),
    ]
