# Generated by Django 4.2.4 on 2023-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_alter_période_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='période',
            name='Fiche',
            field=models.ManyToManyField(to='App1.fiche_paie'),
        ),
    ]
