# Generated by Django 4.2.4 on 2023-12-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_alter_fiche_paie_n_cnss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
