# Generated by Django 4.2.4 on 2023-12-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_alter_poste_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='période',
            old_name='Fiche',
            new_name='Fiches',
        ),
    ]
