# Generated by Django 4.2.4 on 2023-12-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_user_delete_période'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
